name: commits per day CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd commits-per-day    
        npm install
    - run: |
        cd commits-per-day
        npm run build --if-present
    - run: |
        cd commits-per-day
        npm test
      env:
        CI: true
